baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "persian-hugo"
title = "Luna Ranjit"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
url = "contact"
weight = 8
[[menu.main]]
name = "Category"
url = "categories/nature/"
weight = 7
[[menu.main]]
name = "Speaking"
url = "speak"
weight = 5
[[menu.main]]
name = "Organizing"
url = "organize"
weight = 4
[[menu.main]]
name = "Writing"
url = "write"
weight = 3
[[menu.main]]
name = "Consulting"
url = "consult"
weight = 6
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Luna Ranjit"
contact_form_action = "#"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
logo = "images/lr-logo.svg"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
