baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "10"
theme = "persian-hugo"
title = "Luna Ranjit"
[deployment]
order = [".jpg$", ".gif$"]
[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
pattern = "^.+\\.(js|css|svg|ttf)$"
[[deployment.matchers]]
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
pattern = "^.+\\.(png|jpg)$"
[[deployment.matchers]]
contentType = "application/xml"
gzip = true
pattern = "^sitemap\\.xml$"
[[deployment.matchers]]
gzip = true
pattern = "^.+\\.(html|xml|json)$"
[[deployment.targets]]
URL = "s3://amazon-cloudfront-secure-static-site-s3bucketroot-1r1our83wpu6e?region=us-east-1"
cloudFrontDistributionID = "E1MF9E9U3OY2FL"
name = "mydeployment"
[imaging]
anchor = "smart"
bgColor = "#ffffff"
hint = "photo"
quality = 75
resampleFilter = "box"
[imaging.exif]
disableDate = true
disableLatLong = true
excludeFields = ""
includeFields = ""
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Alien"
url = "books"
weight = 9
[[menu.main]]
name = "Collaborating"
url = "collaborate"
weight = 5
[[menu.main]]
name = "Medium"
url = "https://lunaranjit.medium.com"
weight = 8
[[menu.main]]
name = "Speaking"
url = "speak"
weight = 4
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/LunaRanjit"
weight = 7
[[menu.main]]
name = "Contact"
url = "contact"
weight = 6
[[menu.main]]
name = "Writing"
url = "write"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Luna Ranjit"
contact_form_action = "https://formspree.io/f/xknkorvv"
copyright = "Built & maintained by Akoka Inc."
description = "This is meta description"
logo = "images/lr-logo.svg"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
