baseURL = "/"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "10"
theme = "persian-hugo"
title = "Luna Ranjit"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Consulting"
url = "consult"
weight = 5
[[menu.main]]
name = "Speaking"
url = "speak"
weight = 4
[[menu.main]]
name = "Twitter"
url = "https://twitter.com/LunaRanjit"
weight = 7
[[menu.main]]
name = "Medium"
url = "https://lunaranjit.medium.com"
weight = 8
[[menu.main]]
name = "Contact"
url = "contact"
weight = 6
[[menu.main]]
name = "Writing"
url = "write"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Luna Ranjit"
contact_form_action = "https://formspree.io/f/xknkorvv"
copyright = "Built & maintained by Akoka Inc."
description = "This is meta description"
logo = "images/lr-logo.svg"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""

# optimize image size
[imaging]
resampleFilter = "box"
quality = 75
hint = "photo"
anchor = "smart"
bgColor = "#ffffff"
[imaging.exif]
includeFields = ""
excludeFields = ""
disableDate = true
disableLatLong = true

# to deploy to s3 using aws cli
[deployment]
order = [".jpg$", ".gif$"]
[[deployment.targets]]
name = "mydeployment"
URL = "s3://boli-mag.com?region=us-east-1"
cloudFrontDistributionID = "E2DD03QQV50TQH"
[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true
[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
[[deployment.matchers]]
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true
[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
