name: publish to AWS

on:
  push:
    branches:
      - develop # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true

      - name: Build for gh
        run: hugo -b "/lunaranjit/" --minify

      - name: Deploy to gh
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Build for aws
        run: hugo --minify

      - name: Deploy to aws
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true